version: '2.1'

services:

  data:
    image: busybox
    volumes:
      - ./:/code
      - ./:/docs

  mkdocs:
    image: squidfunk/mkdocs-material:latest
    env_file: ./environment.env
    volumes_from: [data]
    ports:
      - "8000:8000"
