site_name: Erdiko Documentation
site_description: Erdiko Documentation
site_author: Arroyo Labs

pages:
    - Home: index.md
    - Quick Start: framework/quickstart.md
    - Framework:
        - 'Overview': framework/index.md
        - 'Documentation': framework/documentation.md
        - 'Databases': framework/databases.md
        - 'Example App': framework/example.md
    - User Admin:
        - 'Overview': user-admin/index.md
        - 'Extending': user-admin/extending.md
        - 'Angular UI': user-admin/angular.md
        - 'Extending Angular UI': user-admin/extending-angular.md
        - 'Contributing': user-admin/contributing.md
    - Users:
        - 'Overview': users/index.md
        - 'Ajax endpoints': users/ajax.md
        - 'Models': users/models.md
        - 'Extending': users/extending.md
    - Authorize:
        - 'Overview': authorize/index.md
        - 'Security': authorize/security.md
        - 'Extending': authorize/extending.md
    - Authenticate:
        - 'Overview': authenticate/index.md
        - 'Extending': authenticate/extending.md
    - Help (Learn More):
        - Submitting Issues: help/index.md
        - Coding style guide: help/style-guide.md
        - About Us: help/about.md
        - Contributing: help/contributing.md

theme: material

extra_css:
  - 'stylesheets/extra.css'

google_analytics:
      - 'UA-32448130-2'
      - auto

markdown_extensions:
  - admonition
  - toc(permalink=true)

extra:
  palette:
    primary: grey
    accent: green
  social:
    - type: github
      link: https://github.com/erdiko
    - type: twitter
      link: https://twitter.com/arroyolabs
    - type: instagram
      link: https://www.instagram.com/arroyolabs
  logo: images/logo.png
